version: "3"
services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: "mongodb"
    env_file: ./containerConfig/mongodb.env
    volumes:
      - ./containerConfig/initMongo.js:/docker-entrypoint-initdb.d/initMongo.js
      - ./data/mongdb:/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null # --quiet
